### ISSUE TITLE
Spec Dynamic Network-weight Scaling V2

### ISSUE THREAD

**Issue by AngelaKTE** [TE-Academy/Reputation-based_Weighted_Voting#11]
Doc: [https://docs.google.com/document/d/1og3oWZGYKuf24jBDV0Q0Qo8KeOLV0deAqjUWWNyoslk/edit?usp=sharing](https://docs.google.com/document/d/1og3oWZGYKuf24jBDV0Q0Qo8KeOLV0deAqjUWWNyoslk/edit?usp=sharing)

**Comment by AngelaKTE** [comment]
test comment made in Github

**Comment by eightarmsninebrains** [comment]
I propose this issue be closed. @AngelaKTE @marthendalnunes
