### ISSUE TITLE
Specify Bonded Reputation Weight Mechanism V1

### ISSUE THREAD

**Issue by AngelaKTE** [TE-Academy/Reputation-based_Weighted_Voting#12]
#### Description

Development ON HOLD

Specify the weighting mechanisms.

Final specification has to include:

- [ ] Use Case
- [ ] Human Language description, including system properties
- [ ] Formal specification
- [ ] Implementation details (e.g. NFT smart contract address, wallet blacklisting etc.)
- [ ] Test cases to test implementation Math vs. Python vs. Javascript

**Files**

Draft is here: [https://docs.google.com/document/d/1PLnq76WbQ5tv5eqnpZ6cpB0mp2MVvW86vsl2yOKoPRE/edit?usp=sharing](https://docs.google.com/document/d/1PLnq76WbQ5tv5eqnpZ6cpB0mp2MVvW86vsl2yOKoPRE/edit?usp=sharing)

**Comment by eightarmsninebrains** [comment]
I'd be OK if the Issue is Closed. Most "obvious" Bonding Curves are going to turn out to be proportional-weighting with each group consisting of just one NFT.  The more exotic ones that we could play with are probably too far afield for the scope of this project.
