### ISSUE TITLE
Add Community Standards to Github repo

### ISSUE THREAD

**Issue by AngelaKTE** [TE-Academy/Reputation-based_Weighted_Voting#30]
### Descriptions

Check community standards and add

* contributing policy
* code of conduct
* issue template
* security policy
* pull request template

**Comment by eightarmsninebrains** [comment]
Can this be closed?

**Comment by AngelaKTE** [comment]
- add what is the prerequisite to get a PR accepted @eightarmsninebrains @marthendalnunes

**Comment by AngelaKTE** [comment]
Solved and closed
