### ISSUE TITLE
HH Index - plot square chart (Metrics discussion)

### ISSUE THREAD

**Issue by AngelaKTE** [TE-Academy/Reputation-based_Weighted_Voting#49]
#### Description

The Herfindahl-Hirschman Index (HHI) is great to understand how concentrated voting weights are in a community. Could we plot the square chart to show the concentration visually.

TE Academy Demo - Note: I'd like to use it to display to voting power of the 537 voters in our ecosystem, we might have to filter down, see issue [TE-64](https://linear.app/te-academy/issue/TE-64/create-plutocracy-demo-te-academy-fellowship-voting-example)

 

![Screenshot 2024-09-05 at 19.44.30.png](https://uploads.linear.app/53fe8ba2-4864-46b3-b245-3bf76b17a5c0/b9ebbe6e-6ba7-4b81-a9cd-8ceaaed158b7/4827b88b-2129-4264-807f-49a8c27752d1?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzUzZmU4YmEyLTQ4NjQtNDZiMy1iMjQ1LTNiZjc2YjE3YTVjMC9iOWViYmU2ZS02YmE3LTRiODEtYTljZC04Y2VhYWVkMTU4YjcvNDgyN2I4OGItMjEyOS00MjY0LTgwN2YtNDlhOGMyNzc1MmQxIiwiaWF0IjoxNzI1NTU4MzEyLCJleHAiOjMzMjk2MTE4MzEyfQ.VXB7lPzWMNV7T3hYiDEPYQphv5eP8n5_f9viOy5498M "=531x")

#### Todo

- [ ] @eightarmsninebrains to update HH Index in `plutocracy.py` to plot Square chart
- [ ] @akrtws to include comment in writeup

**Comment by eightarmsninebrains** [comment]
The graphic is mainly meant to demonstrate how the overall number is calculated. I think other graphics are more informative re: the proportion of voter influence.

**Comment by eightarmsninebrains** [comment]
I propose that we close this Issue.

**Comment by AngelaKTE** [comment]
In the future:
- consider histogram with weights alternatively
